<?php
/**
 * SettingsResponse
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  LiltConnectorSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lilt Connector Plugin API
 *
 * This document describes the Plugin API for Lilt's Connector platform. The Plugin API is intented to be used by developers who wish to build integrations into their desired systems. The purpose of this API is to enable content transfer and status monitoring for localization projects.  - Read more about the concepts and workflows in the   [user guide](/docs/api/v1.0). - Test the API interactively via [Swagger UI](/api/v1.0/ui).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LiltConnectorSDK\Model;

use \ArrayAccess;
use \LiltConnectorSDK\ObjectSerializer;

/**
 * SettingsResponse Class Doc Comment
 *
 * @category Class
 * @package  LiltConnectorSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SettingsResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Settings_Response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'project_prefix' => 'string',
        'project_name_template' => 'string',
        'lilt_translation_workflow' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'project_prefix' => null,
        'project_name_template' => null,
        'lilt_translation_workflow' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'project_prefix' => 'project_prefix',
        'project_name_template' => 'project_name_template',
        'lilt_translation_workflow' => 'lilt_translation_workflow'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'project_prefix' => 'setProjectPrefix',
        'project_name_template' => 'setProjectNameTemplate',
        'lilt_translation_workflow' => 'setLiltTranslationWorkflow'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'project_prefix' => 'getProjectPrefix',
        'project_name_template' => 'getProjectNameTemplate',
        'lilt_translation_workflow' => 'getLiltTranslationWorkflow'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const LILT_TRANSLATION_WORKFLOW_INSTANT = 'INSTANT';
    const LILT_TRANSLATION_WORKFLOW_VERIFIED = 'VERIFIED';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLiltTranslationWorkflowAllowableValues()
    {
        return [
            self::LILT_TRANSLATION_WORKFLOW_INSTANT,
            self::LILT_TRANSLATION_WORKFLOW_VERIFIED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['project_prefix'] = $data['project_prefix'] ?? null;
        $this->container['project_name_template'] = $data['project_name_template'] ?? null;
        $this->container['lilt_translation_workflow'] = $data['lilt_translation_workflow'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getLiltTranslationWorkflowAllowableValues();
        if (!is_null($this->container['lilt_translation_workflow']) && !in_array($this->container['lilt_translation_workflow'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'lilt_translation_workflow', must be one of '%s'",
                $this->container['lilt_translation_workflow'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets project_prefix
     *
     * @return string|null
     */
    public function getProjectPrefix()
    {
        return $this->container['project_prefix'];
    }

    /**
     * Sets project_prefix
     *
     * @param string|null $project_prefix A string value to include in the Project name.
     *
     * @return self
     */
    public function setProjectPrefix($project_prefix)
    {
        $this->container['project_prefix'] = $project_prefix;

        return $this;
    }

    /**
     * Gets project_name_template
     *
     * @return string|null
     */
    public function getProjectNameTemplate()
    {
        return $this->container['project_name_template'];
    }

    /**
     * Sets project_name_template
     *
     * @param string|null $project_name_template The template string to use when generating Project names.  The available template options are:  - **today** - Today's date. Formatted as YYYY-MM-DD. - **trglocale** - The target locale for the given project. - **filename** - The name of the current file being uploaded. - **project_prefix** - The project_prefix value provided in the   configuration. - **project_name** - The project_name value assigned to the file in   the code. - **connector_id** - The Connector ID. - **connector_type** - The Connector Type (e.g. \"xtm\", \"salesforce\").
     *
     * @return self
     */
    public function setProjectNameTemplate($project_name_template)
    {
        $this->container['project_name_template'] = $project_name_template;

        return $this;
    }

    /**
     * Gets lilt_translation_workflow
     *
     * @return string|null
     */
    public function getLiltTranslationWorkflow()
    {
        return $this->container['lilt_translation_workflow'];
    }

    /**
     * Sets lilt_translation_workflow
     *
     * @param string|null $lilt_translation_workflow lilt_translation_workflow
     *
     * @return self
     */
    public function setLiltTranslationWorkflow($lilt_translation_workflow)
    {
        $allowedValues = $this->getLiltTranslationWorkflowAllowableValues();
        if (!is_null($lilt_translation_workflow) && !in_array($lilt_translation_workflow, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'lilt_translation_workflow', must be one of '%s'",
                    $lilt_translation_workflow,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['lilt_translation_workflow'] = $lilt_translation_workflow;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


