<?php
/**
 * ServicesApiJobsPreviewFileProcessing400ResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LiltConnectorSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lilt Connector Plugin API
 *
 * This document describes the Plugin API for Lilt's Connector platform. The Plugin API is intented to be used by developers who wish to build integrations into their desired systems. The purpose of this API is to enable content transfer and status monitoring for localization projects.  - Read more about the concepts and workflows in the   [user guide](/docs/api/v1.0). - Test the API interactively via [Swagger UI](/api/v1.0/ui).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LiltConnectorSDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ServicesApiJobsPreviewFileProcessing400ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ServicesApiJobsPreviewFileProcessing400Response
 * @package     LiltConnectorSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ServicesApiJobsPreviewFileProcessing400ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ServicesApiJobsPreviewFileProcessing400Response"
     */
    public function testServicesApiJobsPreviewFileProcessing400Response()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
